"""patch

Revision ID: 1ad910088ec4
Revises: e40739d0447d
Create Date: 2024-12-12 22:28:04.990119

"""

# revision identifiers, used by Alembic.
revision = "1ad910088ec4"
down_revision = "e40739d0447d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
