"""devices

Revision ID: 269c1385ab66
Revises: bbadd04c8ab6
Create Date: 2024-12-13 22:20:07.253762

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "269c1385ab66"
down_revision = "bbadd04c8ab6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manufacturers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifier", sa.Text(), nullable=True),
        sa.Column("manufacturer_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("models", sa.JSON(), nullable=True),
        sa.Column("released", sa.Date(), nullable=True),
        sa.Column("discontinued", sa.Date(), nullable=True),
        sa.Column("hardware_info", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier"),
    )
    op.create_table(
        "map_patch_to_device",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patch_id", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patch_id"],
            ["patches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patch_id", "device_id", name="unique_patch_id_device_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_patch_to_device")
    op.drop_table("devices")
    op.drop_table("manufacturers")
    # ### end Alembic commands ###
