"""patch

Revision ID: bbadd04c8ab6
Revises: 1ad910088ec4
Create Date: 2024-12-12 22:42:10.114777

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bbadd04c8ab6"
down_revision = "1ad910088ec4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patches", sa.Column("major", sa.Integer(), nullable=True))
    op.add_column("patches", sa.Column("minor", sa.Integer(), nullable=True))
    op.add_column("patches", sa.Column("patch", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("patches", "patch")
    op.drop_column("patches", "minor")
    op.drop_column("patches", "major")
    # ### end Alembic commands ###
