"""released

Revision ID: e40739d0447d
Revises: f33b621cdd08
Create Date: 2024-12-12 14:34:19.079171

"""

# revision identifiers, used by Alembic.
revision = "e40739d0447d"
down_revision = "f33b621cdd08"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
