"""patches

Revision ID: f33b621cdd08
Revises:
Create Date: 2024-12-12 14:15:19.555412

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f33b621cdd08"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capecs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("capec_id", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("extended_description", sa.Text(), nullable=True),
        sa.Column("likelihood_of_attack", sa.Text(), nullable=True),
        sa.Column("severity", sa.Text(), nullable=True),
        sa.Column("execution_flow", sa.JSON(), nullable=True),
        sa.Column("prerequisites", sa.JSON(), nullable=True),
        sa.Column("skills_required", sa.JSON(), nullable=True),
        sa.Column("resources_required", sa.JSON(), nullable=True),
        sa.Column("consequences", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capec_id"),
    )
    op.create_table(
        "cves",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("published", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("cvss", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cve_id"),
    )
    op.create_table(
        "cwes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cwe_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("extended_description", sa.Text(), nullable=True),
        sa.Column("likelihood_of_exploit", sa.Text(), nullable=True),
        sa.Column("background_details", sa.JSON(), nullable=True),
        sa.Column("potential_mitigations", sa.JSON(), nullable=True),
        sa.Column("detection_methods", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cwe_id"),
    )
    op.create_table(
        "patches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("os", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.Column("build", sa.Text(), nullable=True),
        sa.Column("released", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("build"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "map_capec_to_cwe",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("capec_id", sa.Integer(), nullable=True),
        sa.Column("cwe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["capec_id"],
            ["capecs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cwe_id"],
            ["cwes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capec_id", "cwe_id", name="unique_capec_id_cwe_id"),
    )
    op.create_table(
        "map_cve_to_patch",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.Integer(), nullable=True),
        sa.Column("patch_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cve_id"],
            ["cves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patch_id"],
            ["patches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cve_id", "patch_id", name="unique_cve_id_patch_id"),
    )
    op.create_table(
        "map_cwe_to_cve",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cwe_id", sa.Integer(), nullable=True),
        sa.Column("cve_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cve_id"],
            ["cves.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cwe_id"],
            ["cwes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cwe_id", "cve_id", name="unique_cwe_id_cve_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("map_cwe_to_cve")
    op.drop_table("map_cve_to_patch")
    op.drop_table("map_capec_to_cwe")
    op.drop_table("users")
    op.drop_table("patches")
    op.drop_table("cwes")
    op.drop_table("cves")
    op.drop_table("capecs")
    # ### end Alembic commands ###
